- hosts: localhost
  become: true
  tasks:
  - name: Update system
    apt:
      update_cache: yes
      upgrade: dist
  - name: Install dependencies
    apt:
      name:
        - g++
        - gcc-6
        - freeglut3-dev
        - build-essential
        - libx11-dev
        - libxmu-dev
        - libxi-dev
        - libglu1-mesa
        - libglu1-mesa-dev
  - name: Blacklist nouveau
    shell: "echo 'blacklist nouveau\noptions nouveau modeset=0' > /etc/modprobe.d/blacklist-nouveau.conf"
    args:
      creates: /etc/modprobe.d/blacklist-nouveau.conf
    register: nouveau
  - name: Remake initramfs
    command: update-initramfs -u
    when: nouveau.changed
  - name: Install nvidia drivers
    command: ubuntu-drivers autoinstall
  - name: Check if CUDA is downloaded
    stat:
      path: /etc/apt/preferences.d/cuda-repository-pin-600
    register: cuda
  - name: Download CUDA pin
    get_url: 
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
      dest: /etc/apt/preferences.d/cuda-repository-pin-600
    when: cuda.stat.exists == False
  - name: Add CUDA key
    apt_key:
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
      state: present
  - name: Add CUDA repository
    apt_repository:
      repo: deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /
      state: present
  - name: Install CUDA and CUDNN
    apt:
      name:
        - cuda
        - cuda-10-0
        - libcudnn7
        - libcudnn7-dev
        - libnccl2
        - libc-ares-dev
      state: present
  - name: CUDA10 NCCL directory
    file:
      path: "/usr/local/cuda-10.0/nccl/lib"
      state: directory
      mode: '0755'
  - name: NCCL symlink
    file:
      src: "/usr/lib/x86_64-linux-gnu/libnccl.so.2"
      dest: "/usr/local/cuda/nccl/lib/libnccl.so.2"
      state: link
  - name: CUNDD symlink
    file:
      src: "/usr/lib/x86_64-linux-gnu/libcudnn.so.7"
      dest: "/usr/local/cuda-10.0/lib64/libcudnn.so.7"
      state: link
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - name: Install deep learning python libraries
    pip:
      executable: pip3
      name:
        - atari-py
        - box2d-py
        - gym
        - gym-ple
        - keras
        - matplotlib
        - numpy
        - opencv-python
        - pandas
        - PyOpenGL
        - pybullet
        - roboschool
        - scipy
        - tensorflow-gpu
        - torch
        - torchvision
