- hosts: localhost
  become: true
  tasks:
  - name: Update system
    apt:
      update_cache: yes
      upgrade: dist
  - name: Install dependencies
    apt:
      name:
        - g++
        - gcc-6
        - freeglut3-dev
        - build-essential
        - libx11-dev
        - libxmu-dev
        - libxi-dev
        - libglu1-mesa
        - libglu1-mesa-dev
  - name: Blacklist nouveau
    shell: "echo 'blacklist nouveau\noptions nouveau modeset=0' > /etc/modprobe.d/blacklist-nouveau.conf"
    args:
      creates: /etc/modprobe.d/blacklist-nouveau.conf
    register: nouveau
  - name: Remake initramfs
    command: update-initramfs -u
    when: nouveau.changed
  - name: Install nvidia drivers
    command: ubuntu-drivers autoinstall
  - name: Check if CUDA is downloaded
    stat:
      path: /etc/apt/preferences.d/cuda-repository-pin-600
    register: cuda
  - name: Download CUDA pin
    get_url: 
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
      dest: /etc/apt/preferences.d/cuda-repository-pin-600
    when: cuda.stat.exists == False
  - name: Add CUDA key
    apt_key:
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
      state: present
  - name: Add CUDA repository
    apt_repository:
      repo: deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /
      state: present
  - name: Install CUDA
    apt:
      name: cuda
      state: present
  - name: Install deep learning python libraries
    pip:
      executable: pip3
      name:
        - atari-py
        - box2d-py
        - gym
        - gym-ple
        - keras
        - matplotlib
        - numpy
        - opencv-python
        - pandas
        - PyOpenGL
        - roboschool
        - scipy
        - tensorflow-gpu
        - torch
        - torchvision
